// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRNdu3jdZEFUpyGG4pzRpFeKvfTjUoJo',
    appId: '1:342327056544:web:78d0ede6f3670a359511c5',
    messagingSenderId: '342327056544',
    projectId: 'palahi-capstone',
    authDomain: 'palahi-capstone.firebaseapp.com',
    storageBucket: 'palahi-capstone.firebasestorage.app',
    measurementId: 'G-DWMX84S10M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAxowbO7Df94OM7agvYp680DM-xim3CwU',
    appId: '1:342327056544:android:490a468e80531bb19511c5',
    messagingSenderId: '342327056544',
    projectId: 'palahi-capstone',
    storageBucket: 'palahi-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMO3K7dTRG4GxDFV2YDNAr6F1ZY_IuXg',
    appId: '1:342327056544:ios:8f80a916f476c52d9511c5',
    messagingSenderId: '342327056544',
    projectId: 'palahi-capstone',
    storageBucket: 'palahi-capstone.firebasestorage.app',
    iosBundleId: 'com.example.palahi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuMO3K7dTRG4GxDFV2YDNAr6F1ZY_IuXg',
    appId: '1:342327056544:ios:8f80a916f476c52d9511c5',
    messagingSenderId: '342327056544',
    projectId: 'palahi-capstone',
    storageBucket: 'palahi-capstone.firebasestorage.app',
    iosBundleId: 'com.example.palahi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJRNdu3jdZEFUpyGG4pzRpFeKvfTjUoJo',
    appId: '1:342327056544:web:2ba39fd258425ca89511c5',
    messagingSenderId: '342327056544',
    projectId: 'palahi-capstone',
    authDomain: 'palahi-capstone.firebaseapp.com',
    storageBucket: 'palahi-capstone.firebasestorage.app',
    measurementId: 'G-M92YH7L5L5',
  );
}
